name: atf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_sign_in: 5.3.3
  firebase_auth: 3.3.19
  cloud_firestore: 3.1.17
  latlong: 0.6.1
  flutter_map: 1.1.1
  flutter_map_marker_cluster: 0.5.0
  geoflutterfire: 3.0.3
  geolocator: 9.0.0
  http: ^0.13.5
  flutter_svg: ^1.1.5
  getwidget: ^2.0.4
  flutter_signin_button: ^2.0.0
  cached_network_image: ^3.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
