name: atf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  firebase_core_platform_interface: ^4.8.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_sign_in: ^6.1.5
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  latlong2: ^0.8.1
  flutter_map: ^4.0.0
  flutter_map_marker_cluster: ^1.1.1
  geolocator: ^10.0.0
  http: ^0.13.5
  flutter_svg: ^2.0.7
  getwidget: ^4.0.0
  flutter_signin_button: ^2.0.0
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
